# Generated by Django 4.1.7 on 2023-02-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default=0, max_length=222),
            preserve_default=False,
        ),
    ]
