# Generated by Django 4.1.7 on 2023-02-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('subject', models.CharField(max_length=222)),
                ('description', models.TextField()),
            ],
        ),
    ]
