# Generated by Django 4.1.7 on 2023-02-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
